### PR TITLE
Fix MusicPod breaking  when network manager not available on linux 

### PR DESCRIPTION
**Pull request by freshfieldreds**
Added error checking to the connectivity check function otherwise the function never returns breaking parts of the app if network manager is not on the system. This makes MusicPod work as normal without network manager except it will think it is offline.

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Hi thanks. That could be a solution, or alternatively we could just disable this reactive checking for network if network manager is not available. If there would be a good way to check this. This offline check is not mandatory, I actually thought about removing it because it is also possible to just display it in the UI when neither podcast nor radio api are reachable. Anyways, for now I would prefer to check if network manager is useable on the system and then just default isOnline to true. Brb in 9 hours (working :) )

**Comment by freshfieldreds** [comment]
The last commit sets connectivity result to wifi rather then none when an error occurs which happens instantly when network manager is not available. So now podcasts and radio work completely fine

**Comment by Feichtmeier** [comment]
Hey @freshfieldreds sorry for the late reply
I would prefer to fix this in connectivity_plus instead
I don't think we should overwrite it like this, however I understand that it needs to be useable for you. 
While  looking at your code I noticed I also made a mistake in the latest connectivty plus dep upgrade. Could you change the file to

```dart
import 'dart:async';

import 'package:connectivity_plus/connectivity_plus.dart';
import 'package:flutter/widgets.dart';
import 'package:safe_change_notifier/safe_change_notifier.dart';

class AppModel extends SafeChangeNotifier {
  AppModel({required Connectivity connectivity})
      : _connectivity = connectivity,
        _countryCode = WidgetsBinding
            .instance.platformDispatcher.locale.countryCode
            ?.toLowerCase();

  final String? _countryCode;
  String? get countryCode => _countryCode;

  final Connectivity _connectivity;
  StreamSubscription? _subscription;
  List<ConnectivityResult>? _result;

  bool get isOnline =>
      _result?.contains(ConnectivityResult.ethernet) == true ||
      _result?.contains(ConnectivityResult.bluetooth) == true ||
      _result?.contains(ConnectivityResult.mobile) == true ||
      _result?.contains(ConnectivityResult.vpn) == true ||
      _result?.contains(ConnectivityResult.wifi) == true;

  Future<void> init() async {
    // TODO: fix https://github.com/fluttercommunity/plus_plugins/issues/1451
    _subscription ??= _connectivity.onConnectivityChanged.listen(
        _updateConnectivity,
        onError: (e) => _result = [ConnectivityResult.wifi]);
    return _connectivity
        .checkConnectivity()
        .then(_updateConnectivity)
        .catchError((e) => _updateConnectivity([ConnectivityResult.wifi]));
  }

  @override
  Future<void> dispose() async {
    await _subscription?.cancel();
    super.dispose();
  }

  void _updateConnectivity(List<ConnectivityResult> result) {
    _result = result;
    notifyListeners();
  }

  bool _showWindowControls = true;
  bool get showWindowControls => _showWindowControls;
  void setShowWindowControls(bool value) {
    _showWindowControls = value;
    notifyListeners();
  }

  bool? _fullScreen;
  bool? get fullScreen => _fullScreen;
  void setFullScreen(bool? value) {
    if (value == null || value == _fullScreen) return;
    _fullScreen = value;
    notifyListeners();
  }

  bool _lockSpace = false;
  bool get lockSpace => _lockSpace;
  void setLockSpace(bool value) {
    _lockSpace = value;
    notifyListeners();
  }
}

```

**Comment by freshfieldreds** [comment]
Sorry I have been offline for a while, i'm using network manager now so everything is all good at least on my end

**Pull request closed without merging**
