### PR TITLE
Danish translations

### PR DESCRIPTION
**Pull request by madsrh**
A ton of updated string 🇩🇰

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Yay!
Thanks!

I think you somehow inserted a new line here

    "insertIntoQueue": "Ind

sæt i køen",

**Comment by Feichtmeier** [comment]
some more
Error: The arb file /home/runner/work/musicpod/musicpod/lib/src/l10n/app_da.arb has the following formatting issue: 
FormatException: Control character in string (at line 257, character 38)
    "nonProfitXXXPodcastIndexOnly": "
                                     ^
(tip, install this vscode extension: https://github.com/google/arb-editor)

**Comment by madsrh** [comment]
> Fixed unintended spaces

Yeah, sorry for the noise 🙈 I saw it. It should be good now 🍀

**Comment by madsrh** [comment]
> I should setup something easier for translators some day :)

With my Erfolgsbilanz, I should have double checked before making the PR. Learning everyday is good 😆

**Pull request merged**
