### PR TITLE
Added basic, functional last.fm scrobble integration.

### PR DESCRIPTION
**Pull request by CosmicRaptor**
As requested in #874 I have implemented basic scrobble to last.fm
I added a couple of text fields in the settings to enter your API Key and shared secret, along with proper input validations. There's some padding issue in the enable toggle and the save button that I couldn't figure out however
image

I also accidentally merged the 1.8.0 release in my fork please remove that 🙁

### CODE REVIEW

**Comment by CosmicRaptor** [comment]
Some clarifications
The module waits for 20 seconds from the save button being pressed before calling the last.fm auth API to get a session key. It's only needed once.
But it assumes that within those 20 seconds your browser will open up and you will approve the connection request. There has to be a better way to do this hopefully.

**Comment by Feichtmeier** [comment]
@CosmicRaptor first of all: great job! Thank you for following most of the architecture ideas

I think some things got wrong, even the tags are wrong I wonder what happened there
Could you make a new branch and apply your commit to it? and a new PR? sorry for this but there is a bunch of weird things in this branch I cant fix

**Comment by CosmicRaptor** [comment]
Will do soon!

**Comment by Feichtmeier** [comment]
thanks! make sure to pull a fresh main before you start a new branch

**Pull request closed without merging**
