### PR TITLE
Fix publish, remove CI on main

### PR DESCRIPTION
**Pull request by Feichtmeier**
Okay, continue of #203 , as I was stupid and enabled auto merge without having review as requirement for merge :facepalm: .

Action went quite well until the publish step
https://github.com/ubuntu-flutter-community/musicpod/actions/runs/6627423531/job/18002314633?pr=204#step:8:4231
it failed with 

'override-build' in part 'musicpod' failed with code 1.
Review the scriptlet and make sure it's correct.

Sorry @kenvandine , could you check this PR if anything is wrong here 
I followed https://snapcraft.io/docs/snapcraft-authentication
and
https://github.com/snapcore/action-build
and
https://github.com/snapcore/action-publish
with
grafik

Would be nice if you could try if I made any mistake :laughing: 

TODO:

- [x]  !!! :warning: Reminder for me REMOVE publish action on pull request, renable on push to a new "release" branch

### CODE REVIEW

**Comment by kenvandine** [comment]
@Feichtmeier looking at the latest snap build failure in this PR, it looks like a missing build-package for the snap.

```
:: Run-time dependency libplacebo found: NO (tried pkgconfig and cmake)
::
:: ../src/meson.build:26:13: ERROR: Dependency "libplacebo" not found, tried pkgconfig and cmake
```

Was something added that needs libplacebo?

**Comment by Feichtmeier** [comment]
@kenvandine 
the last "new" thing I added was the gtk command line listener from dennis and jp https://github.com/canonical/gtk.dart 
needed this for the desktop file musicpod %U to open music files from within the file explorer
But the local snap build/push/pull works and I did not install any additional dep. locally

https://github.com/haasn/libplacebo
could be related to maybe a change within mediakit :thinking: 
@alexmercerind sorry to tag you, but is libplacebo needed for mediakit?

**Comment by alexmercerind** [comment]
libplacebo is only for video playback; mostly Vulkan based VO. You can disable it in mpv; there's a compilation flag.

**Comment by Feichtmeier** [comment]
> libplacebo is only for video playback; mostly Vulkan based VO. You can disable it in mpv; there's a compilation flag.

Thanks for the information!

MusicPod uses video for video podcasts

**Comment by alexmercerind** [comment]
It's still not used as we use the GL render API.

**Comment by Feichtmeier** [comment]
> It's still not used as we use the GL render API.

Ah! Thank you for clarifying!

**Comment by kenvandine** [comment]
I think for now it would be best to use the latest stable tag of mpv before the libplacebo depends was added

```
diff --git a/snap/snapcraft.yaml b/snap/snapcraft.yaml
index d651bf5..c10e304 100644
--- a/snap/snapcraft.yaml
+++ b/snap/snapcraft.yaml
@@ -41,6 +41,7 @@ slots:
 parts:
   mpv:
     source: https://github.com/mpv-player/mpv.git
+    source-tag: 'v0.36.0'
     plugin: meson
     meson-parameters:
       - --prefix=/usr
```

**Comment by Feichtmeier** [comment]
very nice, this worked, ty ken!

now there is something wrong with the credentials =) checking

**Comment by Feichtmeier** [comment]
eeeemeeegeeeeed it worked 😆

**Comment by Feichtmeier** [comment]
The produced snap also works, now in edge

Now it only needs a solution for ARM, I think I saw some action for this

**Pull request merged**
