### PR TITLE
feat: add listenbrainz scrobbling support

### PR DESCRIPTION
**Pull request by CosmicRaptor**
Added listenbrainz scrobbling. (#1029)
ListenBrainz icon was taken from [here](https://commons.wikimedia.org/wiki/File:ListenBrainz_Logo_(2020).svg) which is licensed under creative commons.

### CODE REVIEW

**Comment by CosmicRaptor** [comment]
As far as I can tell, I followed their icon design guidelines.
https://github.com/metabrainz/design-system/blob/master/guidelines/design-guidelines.md

**Comment by CosmicRaptor** [comment]
> I just think we might need to call init() again after you activated it or did I miss this?

Umm I don't think we need to, the init method simply reads the key from shared prefs and sets up the listenbrainz model. What edge case do you have in mind where this needs to be called twice?

**Comment by Feichtmeier** [comment]
> > I just think we might need to call init() again after you activated it or did I miss this?
> 
> Umm I don't think we need to, the init method simply reads the key from shared prefs and sets up the listenbrainz model. What edge case do you have in mind where this needs to be called twice?

```dart
 ..registerLazySingleton(
      () => ListenBrainzService(
        settingsService: di<SettingsService>(),
      )..init(),
    )
```

this lazy registration registeres this callback that is called when di<ListenBrainzService>() is called for the first time (in the constructor of th eexposeservice)
and then the address the constructor returtns is saved and is used for later calls of di<ListenBrainzService>()
so this means also init is only called once
so the instance of ListenBrainzService() is created and thats it :) so we need to call it again if the api key changes from null to sth or from sth to sth else

**Comment by CosmicRaptor** [comment]
I fixed it and as a bonus the app will also update the now playing on listenbrainz.

**Pull request merged**
