### PR TITLE
Update app_sv.arb

### PR DESCRIPTION
**Pull request by bittin**
Update Swedish translation
Musicpod 2.0

### CODE REVIEW

**Comment by Feichtmeier** [comment]
@bittin thanks

561 is missing a 
"

And at the end there's one bracket too much

**Comment by bittin** [comment]
> @bittin thanks
> 
> 561 is missing a "
> 
> And at the end there's one bracket too much

Fixed that now, i always forget how Flutter syntax works, thx for the help

**Comment by Feichtmeier** [comment]
116 missing the trailing 

,

**Comment by bittin** [comment]
both those fixed it thanks @Feichtmeier :)

**Pull request merged**
