### PR TITLE
Add swiping to change player view on Android

### LINKED ISSUE #396: Swipe to switch between players on Android
When using Musicpod on an Android device, it would be more intuitive to switch between the bottom player and the full height player by swiping up or down. Right now, you have to click on the bottom player or on a small icon in the corner of the screen to achieve this.

### PR DESCRIPTION
**Pull request by Timo-Schroeder**
Closes #396

### CODE REVIEW

**Comment by Timo-Schroeder** [comment]
I got to the number 150 simply by playing around with it. Do you know if there is a value after which an interaction is generally considered to be a swipe?

Also, should this be an Android exclusive feature or does it make sense to also allow it on iOS?

**Comment by Feichtmeier** [comment]
isMobile is fine for using it on all mobile platforms

but could you make it that you extract the inner widget and then either return the inner widget as it is now if not mobile or wrap it with your gesture detector only if it is mobile?
I dont know about the velocity best values

**Comment by Timo-Schroeder** [comment]
The GestureDetector is now one file further up for the bottom player and in both cases only gets returned on mobile devices.

**Comment by Feichtmeier** [comment]
Thank you!

**Pull request merged**
