### PR TITLE
Audio: switch to audio_metadata_reader for reading metadata

### PR DESCRIPTION
**Pull request by Feichtmeier**

### CODE REVIEW

**Comment by ClementBeal** [comment]
Hi!

If you want to fetch the images from the file, you have to set the `getImage` argument to `true`. Then you'll be able to have the cover!

`readMetadata(File(path), getImage: true).`

Just be aware that if you read metadata for a huge amount of tracks, you'll increase the processing time by a lot. Sometimes they contain covers of 5MB...

**Comment by Feichtmeier** [comment]
Bildschirmfoto 2024-02-17 um 17 22 00

woops sorry :D
very nice
so the only bit for me missing is ogg and opus support 😸 
then I can throw this rust thing out 🌬️  🦀 

this flag is also very interesting because we have a problem here with huge collections and those images
see 
https://github.com/ubuntu-flutter-community/musicpod/issues/264

**Comment by ClementBeal** [comment]
Could you provide me a file of each? I don't have any of them in my library.

Yeah! The flag is very useful. In my app, I only fetch the image in the first track of the album folder. It works quite well!

**Comment by Feichtmeier** [comment]
For opus the user shared this file
https://github.com/ubuntu-flutter-community/musicpod/issues/353#issuecomment-1853119510
i search an ogg

**Comment by Feichtmeier** [comment]
okay here is an old song of myself, just tagged it 
https://drive.google.com/file/d/135qCaLxCzBjZbHgIA7T30xhG0zWOdp8P/view?usp=sharing

**Comment by ClementBeal** [comment]
You can try the version `0.0.3`! It seems to work correctly with your files and some other that I have "found" on the internet.

**Comment by Feichtmeier** [comment]
Bildschirmfoto 2024-02-26 um 08 11 24
Bildschirmfoto 2024-02-26 um 08 12 10

Amazing @ClementBeal 
All formats work! Thank you very much 🙏 
If you don't have any concerns I will add you to the "sponsor them" section in the about section :)
Do you have a sponsor link for github?

**Pull request merged**
