### PR TITLE
make like button respond instantly

### PR DESCRIPTION
**Pull request by freshfieldreds**
Simply turned the like button from a stateless widget to a statefull widget  so it can update when the button is pressed.

### CODE REVIEW

**Comment by Feichtmeier** [comment]
hi,not sure if understand this correctly but the like button updates when you press it, its just animated


https://github.com/ubuntu-flutter-community/musicpod/assets/15329494/51c73801-6024-4dc2-bb46-c414d49dfc6f

**Comment by freshfieldreds** [comment]
Strange, it wasn't working for me, I have to manually reload the widgets for them to rebuild. In fact I just discovered pretty much none of the widgets are rebuilding when the state changes and require a hot reload.

https://github.com/ubuntu-flutter-community/musicpod/assets/138096571/f0ba3aad-06c1-4b85-8e25-214bcf4b89e3

It probably plays into a bigger issue on my system since the last two commits you made caused the app be stuck on the splash screen. Maybe because I don't have network manager?

Since this PR seems to be more of just a band aid over a bigger issue I'll close it and look further into it.

**Comment by Feichtmeier** [comment]
I can't see the video for some reason
What operating system are you running MusicPod on? 
It needs access to the corresponding config directory to persist app state changes to disk 
https://github.com/ubuntu-flutter-community/musicpod/blob/main/lib/persistence_utils.dart

**Comment by freshfieldreds** [comment]
MusicPod does have access to that directory, I found the issue to be in the `AppModel` class, the `init()` function never returns because of `_connectivity.checkConnectivity()` -- it can't access network manager because it is not on my system so the future never completes.

```dart
Future<void> init() async {
    _subscription ??=
        _connectivity.onConnectivityChanged.listen(_updateConnectivity);
    return _connectivity.checkConnectivity().then(_updateConnectivity);
}
```

Commenting out the return function allows the code to continue running as it should and resolves all of my previous issues except MusicPod thinks I have no internet so it doesn't give me access to podcasts or radio -- they work fine if i remove the code that prevents that.

So the core issue is the ConnectivityPlus package only uses network manager to check connectivity for linux, as I don't have network manager on my system the `init()` function doesn't return and breaks the app. 

I will implement a fix for this.

**Pull request closed without merging**
