### PR TITLE
[service]: improvement in previous button

### PR DESCRIPTION
**Pull request by soumyaDghosh**
double tap or position is less than 10 seconds => play the previous song
single tap or position more than 10 seconds => play the song from the starting

### CODE REVIEW

**Comment by Feichtmeier** [comment]
from what I see from for example youtubemusic and spotify it works there like this:

- is the position less than X amount back button goes to the previous song
- is the position more than x amount the back button plays the current song again ang jumps to position 0

I would prefer this over your approach with the double tap. So no need for a gesture detector around the icon button and no need to change the signatures of all those methods. You only need to check the position inside the playPrevious method

**Comment by soumyaDghosh** [comment]
> I would prefer this over your approach with the double tap.

The double tap is more for the touch devices than the desktop. I thought to add an `isMobile`, but then just keep it. The `position > 10 seconds` is also there, and it doesn't depend on the double tap. So, should I completely remove the `doubleTap`?

**Comment by Feichtmeier** [comment]
I would prefer to stay on the "convention" like in all modern music players.
All you need to do is change the player_service playPrevious method to:

```dart
  Future<void> playPrevious() async {
    if (queue.$2.isNotEmpty == true &&
        audio != null &&
        queue.$2.contains(audio)) {
      if (_position != null && _position!.inSeconds > 10) {
        setPosition(Duration.zero);
        await seek();
      } else {
        final currentIndex = queue.$2.indexOf(audio!);

        if (currentIndex == 0) {
          return;
        }
        _setAudio(queue.$2.elementAt(currentIndex - 1));
        nextAudio = queue.$2.elementAt(queue.$2.indexOf(audio!) + 1);

        await play();
      }
    }
  }
  ```
  and revert all the rest

**Comment by soumyaDghosh** [comment]
> ```dart
> nextAudio = queue.$2.elementAt(queue.$2.indexOf(audio!) + 1);
> ```

we shouldn't do this here, because, in case of shuffle, it'll not properly. I think we should recall the `_estimateNext()` here.

**Comment by Feichtmeier** [comment]
> > ```dart
> > nextAudio = queue.$2.elementAt(queue.$2.indexOf(audio!) + 1);
> > ```
> 
> we shouldn't do this here, because, in case of shuffle, it'll not properly. I think we should recall the `_estimateNext()` here.

ok! Then you could change this in this PR except this line and revert the rest please

**Comment by soumyaDghosh** [comment]
@Feichtmeier done!

**Comment by soumyaDghosh** [comment]
closing and recreating this PR, accidentally messed it while updating the branch.

**Pull request closed without merging**
