### PR TITLE
Flatpak build tools

### PR DESCRIPTION
**Pull request by 12people**
Everything necessary to build a Flatpak.

It's not appropriate for me to contribute a PR with an actual Flatpak package, as:
1. Flatpak packages are binary files, so should be hosted as Releases on Github rather than inside the repo.
2. Releasing on Flathub requires someone to [propose the app for the Flathub repository](https://github.com/flathub/flathub/wiki/App-Submission#how-to-submit-an-app), which should ideally be the package author. (Especially since, in the future, Flathub will also support donations as direct payments.)
3. Since Flatpak only works with compiled Flutter binaries, a new package needs to be uploaded with each release.

However, what this PR does is make it extremely simple to create a Flatpak release. To do so, just compile the app for x86_64 Linux, add the new release version number to the "flatpak/spec.json" file, and run "dart flatpak_generator.dart spec.json".

This will create everything you need to distribute a new Flatpak release:
- a tar.gz containing the binary to upload as a Github release
- a new Flathub manifest pointing to this new binary package

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Thanks @12people people preferring this package format will be happy 👍 
Intersting thing with this dart file !
Since this is in a flatpak dir I can't see any negative side effects on the flutter app itself or the snap directory

**Review by Feichtmeier — APPROVED** [review]

**Comment by 12people** [comment]
Yeah, it's just an independent script with no dependencies (on purpose). It was easier for me to write this script using Dart than Bash or similar, and I figured that it will also be easier for you to look through and understand.

Thanks a lot for merging this!

**Comment by Feichtmeier** [comment]
I will take a look at the flathub thing! Thanks for this

**Comment by Feichtmeier** [comment]
Sure I will get back to this! Currently a bit away from github "AFG" ; D

In the meantime you can install snapd on fedora with these commands (eh please do not take this the wrong way, I respect any preferences, just want to make sure you are aware):
https://snapcraft.io/docs/installing-snap-on-fedora

**Comment by der-ali** [comment]
@Feichtmeier thanks a lot for the recommendation! I switched though from ubuntu to fedora because i wanted to really get rid of snaps hhhh.

**Comment by Feichtmeier** [comment]
Hehe 😀 yes, bit out of scope xD

Flatpak will come!

**Pull request merged**
